version: '3.8'
services:
  frontend:
    image: registry.chasacademy.dev/chas-challenge-2025/group14/cc.14/frontend:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - cc14-network
    configs:
      - source: registry_auth

  backend:
    image: registry.chasacademy.dev/chas-challenge-2025/group14/cc.14/backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - cc14-network
    configs:
      - source: registry_auth

configs:
  registry_auth:
    external: true

networks:
  cc14-network:
    driver: overlay

