export const fakeProjects = [
    {
      id: 1,
      title: "Frontend React Developer",
      description: "Looking for an experienced React developer.",
      techStack: ["React", "TypeScript", "TailwindCSS"],
      info: "Work on building UI for an e-commerce platform.",
      details: "3 months project, 100% remote.",
      location: "Stockholm",
      duration: "3 months",
      rate: "600 kr/h",
      startDate: "2023-05-15",
      isRemote: true,
      isNew: true,
      isPartTime: false,
      postedAt: new Date("2023-04-15"),
    },
    {
      id: 2,
      title: "Frontend React Developer",
      description: "Looking for an experienced React developer",
      techStack: ["React", "TypeScript", "TailwindCSS"],
      info: "Work on building UI for an e-commerce platform.",
      details: "3 months project, 100% remote.",
      location: "Stockholm",
      duration: "3 months",
      rate: "600 kr/h",
      startDate: "2023-05-15",
      isRemote: true,
      isNew: true,
      isPartTime: false,
      postedAt: new Date("2023-04-15"),
    },
    {
      id: 2,
      title: "Frontend React Developer",
      description: "Looking for an experienced React developer",
      techStack: ["React", "TypeScript", "TailwindCSS"],
      info: "Work on building UI for an e-commerce platform.",
      details: "3 months project, 100% remote.",
      location: "Stockholm",
      duration: "3 months",
      rate: "600 kr/h",
      startDate: "2023-05-15",
      isRemote: true,
      isNew: true,
      isPartTime: false,
      postedAt: new Date("2023-04-15"),
    }
  ];